name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        # go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container: golang:1.13
    steps:
    # - name: Install Go
    #   uses: actions/setup-go@v1
    #   with:
    #     go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v1

    - name: Tesing
      run: |
        make test
    - name: Build binary
      run: |
        make build_linux_amd64